### ISSUE TITLE
Feature Request: Custom (or Shortened) Download Links

### ISSUE THREAD

**Issue by titeishon** [psi-4ward/psitransfer#25]
Hi!

I've been using PsiTransfer for a while now and sometimes I want to transfer files between two computers on the same network but I don't have an account in common or means to copy the download link easily and paste it on the target computer. So I always resort to manually typing the address which is kinda cumbersome.
So having the ability to create custom download links could make it so much easier to remember and type it elsewhere. It also has the added bonus to use vanity urls for important files (e.g. http://server.lan/DellDrivers)

Thanks!

**Comment by psi-4ward** [comment]
This tool is not designed as permanent file storage. See https://github.com/psi-4ward/psitransfer/issues/26#issuecomment-322158114

**Comment by daerup** [comment]
I would also like to see this function implemented. It would make sharing the Uploaded files with friends much more simple. 
Even though the Files are only temporarily on the server, accessing it with a 12 digit id is kind of annoying.

Since Upload.js can't easily be changed, I would suggest implementing this function officially.
