### ISSUE TITLE
IE Retention jumps back

### ISSUE THREAD

**Issue by mStirner** [psi-4ward/psitransfer#40]
In Internet Explorer 11 the Retention selection jump back to the defaults settings after click on upload.

**Comment by greecemunky** [comment]
Confirmed in MS IE 11.
Same happens in MS Edge.

**Comment by stefanvangastel** [comment]
Same in some older versions of Firefox (46) and Chrome (54)

**Comment by psi-4ward** [comment]
Can someone prepare a PR?

**Comment by greecemunky** [comment]
Additionally, another trigger, at least in MS IE 11 and Firefox ESR 45.9.0, is updates to the password input box - either via typing in the password or pressing the generate password button.  As it occurs in both IE and Firefox, I assume the fix for #46 doesn't apply here.

Unfortunately I'm simply a user, not a developer - I don't know why it's failing, all I call tell you what appears to be failing.  However if you have advice for us non-NodeJS / Vue peeps or those who have never debugged JS scripts before on how to assist further, I'm more than happy to try.

**Comment by psi-4ward** [comment]
Pls try the latest version. I could not reproduce this anymore.
