### ISSUE TITLE
IEx: generating passwords doesn't work

### ISSUE THREAD

**Issue by smt-ch** [psi-4ward/psitransfer#46]
Hello
First of all thank you for this great piece of software!
After playing around and done some configurations I realized, that in IEx 11 the button "generate password" is not working - nothing happens.
Perhaps this is a combined problem with Issue #40 (I can confirm this problem in IEx 11)?

Thanks in advance!
Greetings, Andrew

**Comment by t0th0mas** [comment]
Any chance to get this issue fixed?

Thank you,
Thomas

**Comment by Slixor** [comment]
The issue is that the "window.crypto" fuction is only supported by Chrome/Mozila/etc.  Microsoft/IE consider this a "experimental feature" and have therefore called the function "window.msCrypto".

A quick, dirty fix I made, edit upload.js line 1140 with the following:

```
_getRandomByte: function() {
                var t = new Uint8Array(1);
				var fixedcrypto = window.msCrypto;
				if (!fixedcrypto) {
					var fixedcrypto = window.crypto;
				}
                return fixedcrypto.getRandomValues(t), t[0]
            },
            generate: function(t) {
				var fixedcrypto2 = window.msCrypto;
				if (!fixedcrypto2) {
					var fixedcrypto2 = window.crypto;
				}
                return fixedcrypto2 && fixedcrypto2.getRandomValues ? Array.apply(null, {
                    length: t
                }).map(function() {
                    for (var t = void 0;;)
                        if (t = String.fromCharCode(this._getRandomByte()), this._pattern.test(t)) return t
                }, this).join("") : ""
            }
```

Essentially we declare fixedcrypto as window.msCrypto, then check to see if it is null (i.e if chrome was used) and if it is, we delcare it again as window.crypto.

**Comment by psi-4ward** [comment]
Do you like to prepare a pull request?

**Comment by Slixor** [comment]
I cannot as the public\app folder is setup under .gitignore @psi-4ward

**Comment by Slixor** [comment]
@psi-4ward #47 #

**Comment by smt-ch** [comment]
Wow - great fix!
Passwords in IEx 11 are now working like a charme - Thanks alot!
Greetings, Andrew
