### ISSUE TITLE
IE11 download page link not working

### ISSUE THREAD

**Issue by paglia80** [psi-4ward/psitransfer#48]
Hi, thank you for this great software - so simple, so functional.
I'm testing the application with different browser, i see that  in the download page - using IE11 - if i click on the filename nothing happens. Can you help me?
Firefox, chrome, works perfectly.

**Comment by j5k** [comment]
I can report this issue too. With Firefox on Linux and Windows. Microsoft Edge works. 

Thanks for fixing, seems to be an important functionality for this project.

**Comment by psi-4ward** [comment]
Probably someone could prepare a PR?

**Comment by fbatschi** [comment]
It seems there is the same problem on Linux with Firefox 59. Clicking on the filename does not work. Nothing is written in the Console. Chrome on Linux works fine.

**Comment by alaincao** [comment]
Heylow,

I am not sure (yet) how to correctly create a pull request, but here is how to fix that problem:  

In file [Download.vue line 123](https://github.com/psi-4ward/psitransfer/blob/master/app/src/Download.vue#L123), the `aEl.click()` function call [doesn't open the link because you don't add the element to the DOM](https://stackoverflow.com/questions/32285899/anchors-click-function-not-working-in-firefox).

Surround that line with
```javascript
document.body.append( aEl );
aEl.click();
aEl.remove();
```
and it should work
