### ISSUE TITLE
cipher passwords in the json backend files

### ISSUE THREAD

**Issue by kumy** [psi-4ward/psitransfer#91]
The password used to protect the upload are in clear text in the generated json file. It would be better to have them ciphered.

**Comment by Plausible0Bug** [comment]
Given the fact that all uploaded files are not encrypted, neither by client nor by server, potentially because of performance concerns, protecting password seemed pointless.

For a proper encryption protection, file should be encrypted and chunked on client side with the random client generated cipher with enough cryptological strength, then the chunked data be sent to server for storage, thus server have 0 knowledge regarding the actual content.

Upon download client need to import key for decryption after chunked data downloaded.

Then again, you can always zip a file with password before upload.

**Comment by psi-4ward** [comment]
> Upon download client need to import key for decryption after chunked data downloaded.

This is the point of pain. Currently browsers do not have a file-writer-stream so the decryption has to be done in-memory which is not usable for larger files. I think this is the reason why firefox-send limits the file-size.

My idea was to decrypt files >500MB on the server but this breaks e2e-enc is not a really a good workaround.

**Comment by Haocen** [comment]
I wonder how mega.nz does their in browser encryption?

**Comment by psi-4ward** [comment]
I don't know.

**Comment by psi-4ward** [comment]
A solution could be something like https://github.com/jimmywarting/StreamSaver.js
Create a webworker which intercepts the download and responds with the unecrypted data. 

Probably anyone has time and fun to do some experiments ;)

**Comment by martin-braun** [comment]
@psi-4ward In regards of the admin and upload password. Why can't you simply salt and encrypt the password before it's sent in the browser and compare the ciphered string instead? 

@Plausible0Bug It makes perfect sense. I.e. while editing the config file while somebody else watches. The intruder doesn't need access to the file system to steal the passwords with the current methods. You should always avoid clear text passwords when the gate is public. 

If it was used behind a firewall, like when using local database credentials, this would be a different story.
